apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: booking-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: auth
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "1000m"
