apiVersion: v1
kind: Namespace
metadata:
  name: booking-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: booking-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: booking-system
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-data
      containers:
      - name: mysql
        image: mysql:9.2.0
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 3400m
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: engine
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: db_password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - set -ex
            - >-
              mysql -h127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e'SELECT 1'
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: booking-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql