apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking-system

spec:
  type: ClusterIP

  ports:
  - name: booking
    port: 3000
    targetPort: booking
  - name: booking-debug
    port: 3010
    targetPort: booking-debug
  - name: metrics
    port: 4000
    targetPort: metrics
  - name: metrics-debug
    port: 4010
    targetPort: metrics-debug
  - name: prometheus
    port: 4020
    targetPort: metrics-prom
