apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/booking/
  - ./dev-booking-configmap.yaml
patches:
  - path: ./dev-booking-patch-deploy.yaml
  - path: ./dev-booking-patch-service.yaml
images:
  - name: booking-image
    newName: localhost/rmsj/booking
    newTag: 0.0.1
  - name: metrics-image
    newName: localhost/rmsj/metrics
    newTag: 0.0.1
